version: "3.9"

services:
  db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - "5433:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d  
    restart: always

  web:
    build: .
    container_name: library_api
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-72(_^$z3fwreap()k2jb(@f^d^o+8=7c&w=f9-q44s*i#7i+g&
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=library_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ACCESS_TOKEN_HOURS=72
      - REFRESH_TOKEN_DAYS=7
      - TIME_ZONE=America/Bogota
      - LANGUAGE_CODE=es
    depends_on:
      - db
    restart: always

volumes:
  db_data:
